development:
  adapter: postgresql
  encoding: unicode
  database: venmo_dev
  pool: 5
  host: localhost
  username: postgres
  password: foundpass

test:
  adapter: postgresql
  encoding: unicode
  database: venmo_test
  pool: 5
  host: localhost
  username: postgres
  password: foundpass